name: CI/CD Workflow for ReactJS App to EKS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build, Push, and Deploy to EKS
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: sagarmagar0709/react-app  # Replace with your Docker Hub username/repo
      DEPLOYMENT_FILE: k8s/deployment.yaml # Adjust if your path differs

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build React App
      run: npm run build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract Short SHA
      id: vars
      run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Build and Push Docker Image
      run: |
        docker build -t $IMAGE_NAME:$SHORT_SHA .
        docker push $IMAGE_NAME:$SHORT_SHA

    - name: Update Image Tag in Deployment YAML
      run: |
        sed -i "s|image: .*$|image: $IMAGE_NAME:$SHORT_SHA|" $DEPLOYMENT_FILE

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: us-east-1  # change if you're using a different region

    - name: Update kubeconfig for EKS Cluster
      run: |
        aws eks update-kubeconfig --region us-east-1 --name demo-cluster

    - name: Deploy to EKS using kubectl
      run: kubectl apply -f $DEPLOYMENT_FILE
