name: CI/CD Pipeline

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Build, Push & Deploy to EKS
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      CLUSTER_NAME: dev-cluster

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract short SHA
      id: vars
      run: echo "TAG=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Build & Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: sagarmagar070/ai_resume_analyzer:${{ steps.vars.outputs.TAG }}

    - name: Replace image tag in deployment.yml
      run: |
        sed "s|__IMAGE_TAG__|${{ steps.vars.outputs.TAG }}|g" k8s/deployment.yml > k8s/deployment-updated.yml

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_REGION

    - name: Deploy to EKS
      run: kubectl apply -f k8s/deployment-updated.yml

#
